# Generated by Django 5.2.5 on 2025-08-07 10:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_user_is_organizer_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('early_bird', 'Early Bird'), ('student', 'Student')], default='regular', max_length=20),
        ),
    ]
