# Generated by Django 5.2.5 on 2025-08-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_ticket_created_at_ticket_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
    ]
