# Generated by Django 5.2.5 on 2025-08-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_venue_address_remove_venue_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='receipt_file',
            field=models.FilePathField(blank=True, max_length=500, null=True, path='C:\\Users\\Administrator\\Documents\\Zindua\\DJANGO\\event_platform\\receipts'),
        ),
    ]
