# Generated by Django 5.2.5 on 2025-08-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
