# Generated by Django 5.2.5 on 2025-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_booking_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('vip', 'VIP'), ('student', 'Student')], default='regular', max_length=20),
        ),
    ]
